# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: ^frontend/src/client/.*
      - id: trailing-whitespace
        exclude: ^frontend/src/client/.*
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.4.0"
    hooks:
      - id: biome-check
        language_version: 20.18.0
        additional_dependencies: ["@biomejs/biome@1.9.1"]
        exclude: frappe_apps/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        exclude: |
            (?x)^(
                frappe_apps/.*/public/dist/.*|
                .*node_modules.*|
                .*boilerplate.*|
                frappe_apps/.*/templates/includes/.*|
                frappe_apps/.*/public/js/lib/.*
            )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        exclude: |
            (?x)^(
                frappe_apps/.*/public/dist/.*|
                cypress/.*|
                .*node_modules.*|
                .*boilerplate.*|
                frappe_apps/.*/templates/includes/.*|
                frappe_apps/.*/public/js/lib/.*
            )$

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
  autoupdate_schedule: weekly
  skip: []
  submodules: false
